#!/bin/bash
# Taken from https://medium.com/@frontman/how-to-parse-yaml-string-via-command-line-374567512303
function yaml2json() {
    ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' $*;
}

for host in $(yaml2json "$1" | jq 'keys[]' | sed s/\"//g);
do
    if ! test -d "$host";
    then
        echo "Adding $host"
        mkdir "$host"
        touch "${host}/${host}.crt.pem"
        touch "${host}/${host}.key.private.pem"
    fi
done
