profile::kubernetes::deployment_server::tokens:
  admin:
    token: dummy
  mathoid:
    token: dummy
  zotero:
    token: dummy
  graphoid:
    token: dummy
  blubberoid:
    token: dummy
  eventgate-analytics:
    token: dummytoken
  eventgate-main:
    token: dummytoken
  citoid:
    token: dummytoken
  cxserver:
    token: dummytoken
  sessionstore:
    token: dummytoken
  termbox:
    token: dummytoken
  wikifeeds:
    token: dummytoken
  echostore:
    token: dummytoken
  eventgate-logging-external:
    token: dummytoken
  eventstreams:
    token: dummytoken
  eventstreams-internal:
    token: dummytoken
  eventgate-analytics-external:
    token: dummytoken
  changeprop:
    token: dummytoken
  changeprop-jobqueue:
    token: dummytoken
  proton:
    token: dummytoken
  mobileapps:
    token: dummytoken
  recommendation-api:
    token: dummytoken
  push-notifications:
    token: dummytoken
  api-gateway:
    token: dummytoken
  apertium:
    token: dummytoken
  linkrecommendation:
    token: dummytoken
  similar-users:
    token: dummytoken
  shellbox:
    token: dummytoken
  miscweb:
    token: dummytoken

profile::kubernetes::deployment_server_secrets::defaults:
  staging:
    defaultsecret: muchdefault
  codfw:
    main_app:
      redis:
        defaultsecret: muchdefault

profile::kubernetes::deployment_server_secrets::services:
  zotero:
    staging:
      loooldata: a
      test: data
      defaultsecret: notdefault
    eqiad:
      main_app:
        salt: dummy
    codfw:
      main_app:
        salt: dummy
  changeprop:
    eqiad:
      main_app:
        redis:
          pass: dummy
    codfw:
      main_app:
        redis:
          pass: dummy
          defaultsecret: notdefault
    staging:
      main_app:
        redis:
          pass: dummy
# The push-notifications keys/data are fake, even though they look real.
  push-notifications:
    eqiad:
      main_app:
        apns:
          keyId: 'KEY_ID'
          teamId: 'TEAM_ID'
          data: |-
            -----BEGIN PRIVATE KEY-----
            MIIEogIBAAKCAQEA2ZUlwz6geaDZweWLH1yLjiRQ3l5oDl4gJBylCHE4XO3BTzVO
            3uvwduq9AvRVHBPhzWlBRzFMb9q8n6jlIdTkixdCE+LcJc2DYUfL58uiPtYP5fub
            bdkT8D9qtRkw/E8XL6zYltsLCajFMn96CgIywRMNb362ewpRrzz0jKpJjacPjgoV
            bH/68GImhRnD4gtdfzQ2J2gQ1rgnABHOZUgcw5aN1st71eqwEdJZqlbaJsaL64fG
            Rv0SZFvXrbHPrWipSMv4nMlhCPD+OdvJwE0zQ3CVkORrm545E7GE+meEXEjFVzge
            fulrPWSnZgxFIwrNBNehk9+0MwTd9fbk8CpInwIDAQABAoIBACgBhmn5z+PNMXy3
            SfdAOuCtyLi6PwO1Rs+c/LMqriRYCt0XfiL62sHis1Ihvqxk83WjTr9aTyWZ4Giy
            0z5/OG5inmGtqrDAstFmNBWwmWpYTaAJvTBbY5Ee9+3IbftWR3samtBSAhuKjoeU
            bMn+UXqymBvR/pds9Ev2NzjN7qw+nn1gcupPNw0fpcEk7U4HT85oe2XmDOaCaoXB
            4ovLxzdRVnkHdNfp3tDMqVHLZrPP4bXbLi1+Tt4yF/JbDDXbY1pu+tebLW+xL5Zr
            iLD5NZV2GH+EHj1oWB5utfVO2c+FDjJAvnceWnfEYuJ+p5g6nzV/C7o2lw7qnmpd
            HT0v5MECgYEA9jq/FjPMd+GRXMYV6rp9B9MGisRSA08lt0hDs5iKU2r5TB3c0hAq
            z3+suKJ7/8VxBxNmtduUt4r4rvAyB8gG5hWQtNSgis8COVC2QLBRRcvecjTcUhhA
            bOS8O0Sg8zVdfzeSaTMbQLFVtOYcBCvP7RYVXFn3CGOjgQZ64axfCdECgYEA4jdm
            WqSfQgqjAhIRWbU0DDbF/7iLZGiyUv3G4AA7XUWRMbItjO91jCE4feywT3SyaVEJ
            JEpXI4849sNMkZ4XwylTCCgO5WBqQmQWeHAuxp4H4LOW9Hjmy1Ev6lIJChy0AD4t
            Z6DEZwHdLZWIcyCRWmKfZyYPOYYB8g2em5VvV28CgYBbO9svw9OgG8E7qd3XEnBf
            ZM6IvkNRHJNx/OGw+vVOAVYL4QjAAOOL7Ne3teTSGXtOzt6AxbKt611HnJI9Fd2Q
            hS8QAbTWmetOB1zwTSRgAzESCgoUlQ3SC1K/dydX1k8lYxbpydjwOIT0OUrqNL2f
            ME6L4H3K6vhbR2ZilfbE8QKBgER6nsprsSYt0CCtVYFBgEr+PbvmopO3uduzpQNk
            LpRSndxcYruaNYxA9jfwcYLsAaIt/MV2l6BVF9pjTod6Qxk6Jj9+2NuI70G/yKmW
            1CId7qaP1u+UtdDwd7/IK6JbBAZazCXlne7Muqa08IRhZH7nAfgYpl00etxKUSwp
            9XWTAoGAFoJENS2q5k0b86blOYiBBTXQo2SreC8Uidr3PjRSR1koamhsnbNz9vZ+
            MhXeq4puvrUxw10zqmogho81HuYJrSsm3K8cIrRcFx7Tq+8G/Lnp0vNKya04GMDI
            NEqE55cyBebb+KpQILZU1ZZY32W7/5xys6sZcJVkiGhmCdLEMmY=
            -----END PRIVATE KEY-----
        google: |-
          {
          "type": "service_account",
          "project_id": "dummyproject",
          "private_key_id": "1111111111111111111111111111111111111111",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEogIBAAKCAQEA2ZUlwz6geaDZweWLH1yLjiRQ3l5oDl4gJBylCHE4XO3BTzVO\n3uvwduq9AvRVHBPhzWlBRzFMb9q8n6jlIdTkixdCE+LcJc2DYUfL58uiPtYP5fub\nbdkT8D9qtRkw/E8XL6zYltsLCajFMn96CgIywRMNb362ewpRrzz0jKpJjacPjgoV\nbH/68GImhRnD4gtdfzQ2J2gQ1rgnABHOZUgcw5aN1st71eqwEdJZqlbaJsaL64fG\nRv0SZFvXrbHPrWipSMv4nMlhCPD+OdvJwE0zQ3CVkORrm545E7GE+meEXEjFVzge\nfulrPWSnZgxFIwrNBNehk9+0MwTd9fbk8CpInwIDAQABAoIBACgBhmn5z+PNMXy3\nSfdAOuCtyLi6PwO1Rs+c/LMqriRYCt0XfiL62sHis1Ihvqxk83WjTr9aTyWZ4Giy\n0z5/OG5inmGtqrDAstFmNBWwmWpYTaAJvTBbY5Ee9+3IbftWR3samtBSAhuKjoeU\nbMn+UXqymBvR/pds9Ev2NzjN7qw+nn1gcupPNw0fpcEk7U4HT85oe2XmDOaCaoXB\n4ovLxzdRVnkHdNfp3tDMqVHLZrPP4bXbLi1+Tt4yF/JbDDXbY1pu+tebLW+xL5Zr\niLD5NZV2GH+EHj1oWB5utfVO2c+FDjJAvnceWnfEYuJ+p5g6nzV/C7o2lw7qnmpd\nHT0v5MECgYEA9jq/FjPMd+GRXMYV6rp9B9MGisRSA08lt0hDs5iKU2r5TB3c0hAq\nz3+suKJ7/8VxBxNmtduUt4r4rvAyB8gG5hWQtNSgis8COVC2QLBRRcvecjTcUhhA\nbOS8O0Sg8zVdfzeSaTMbQLFVtOYcBCvP7RYVXFn3CGOjgQZ64axfCdECgYEA4jdm\nWqSfQgqjAhIRWbU0DDbF/7iLZGiyUv3G4AA7XUWRMbItjO91jCE4feywT3SyaVEJ\nJEpXI4849sNMkZ4XwylTCCgO5WBqQmQWeHAuxp4H4LOW9Hjmy1Ev6lIJChy0AD4t\nZ6DEZwHdLZWIcyCRWmKfZyYPOYYB8g2em5VvV28CgYBbO9svw9OgG8E7qd3XEnBf\nZM6IvkNRHJNx/OGw+vVOAVYL4QjAAOOL7Ne3teTSGXtOzt6AxbKt611HnJI9Fd2Q\nhS8QAbTWmetOB1zwTSRgAzESCgoUlQ3SC1K/dydX1k8lYxbpydjwOIT0OUrqNL2f\nME6L4H3K6vhbR2ZilfbE8QKBgER6nsprsSYt0CCtVYFBgEr+PbvmopO3uduzpQNk\nLpRSndxcYruaNYxA9jfwcYLsAaIt/MV2l6BVF9pjTod6Qxk6Jj9+2NuI70G/yKmW\n1CId7qaP1u+UtdDwd7/IK6JbBAZazCXlne7Muqa08IRhZH7nAfgYpl00etxKUSwp\n9XWTAoGAFoJENS2q5k0b86blOYiBBTXQo2SreC8Uidr3PjRSR1koamhsnbNz9vZ+\nMhXeq4puvrUxw10zqmogho81HuYJrSsm3K8cIrRcFx7Tq+8G/Lnp0vNKya04GMDI\nNEqE55cyBebb+KpQILZU1ZZY32W7/5xys6sZcJVkiGhmCdLEMmY=\n-----END PRIVATE KEY-----\n",
          "client_email": "fffffffffffffffffffffff@g111111111111111111111111.com",
          "client_id": "111111111111111111111",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/1111111111111111111111111111111111111111111111111111111111111111111111111"
          }
    codfw:
      main_app:
        apns:
          keyId: 'KEY_ID'
          teamId: 'TEAM_ID'
          data: |-
            -----BEGIN PRIVATE KEY-----
            MIIEogIBAAKCAQEA2ZUlwz6geaDZweWLH1yLjiRQ3l5oDl4gJBylCHE4XO3BTzVO
            3uvwduq9AvRVHBPhzWlBRzFMb9q8n6jlIdTkixdCE+LcJc2DYUfL58uiPtYP5fub
            bdkT8D9qtRkw/E8XL6zYltsLCajFMn96CgIywRMNb362ewpRrzz0jKpJjacPjgoV
            bH/68GImhRnD4gtdfzQ2J2gQ1rgnABHOZUgcw5aN1st71eqwEdJZqlbaJsaL64fG
            Rv0SZFvXrbHPrWipSMv4nMlhCPD+OdvJwE0zQ3CVkORrm545E7GE+meEXEjFVzge
            fulrPWSnZgxFIwrNBNehk9+0MwTd9fbk8CpInwIDAQABAoIBACgBhmn5z+PNMXy3
            SfdAOuCtyLi6PwO1Rs+c/LMqriRYCt0XfiL62sHis1Ihvqxk83WjTr9aTyWZ4Giy
            0z5/OG5inmGtqrDAstFmNBWwmWpYTaAJvTBbY5Ee9+3IbftWR3samtBSAhuKjoeU
            bMn+UXqymBvR/pds9Ev2NzjN7qw+nn1gcupPNw0fpcEk7U4HT85oe2XmDOaCaoXB
            4ovLxzdRVnkHdNfp3tDMqVHLZrPP4bXbLi1+Tt4yF/JbDDXbY1pu+tebLW+xL5Zr
            iLD5NZV2GH+EHj1oWB5utfVO2c+FDjJAvnceWnfEYuJ+p5g6nzV/C7o2lw7qnmpd
            HT0v5MECgYEA9jq/FjPMd+GRXMYV6rp9B9MGisRSA08lt0hDs5iKU2r5TB3c0hAq
            z3+suKJ7/8VxBxNmtduUt4r4rvAyB8gG5hWQtNSgis8COVC2QLBRRcvecjTcUhhA
            bOS8O0Sg8zVdfzeSaTMbQLFVtOYcBCvP7RYVXFn3CGOjgQZ64axfCdECgYEA4jdm
            WqSfQgqjAhIRWbU0DDbF/7iLZGiyUv3G4AA7XUWRMbItjO91jCE4feywT3SyaVEJ
            JEpXI4849sNMkZ4XwylTCCgO5WBqQmQWeHAuxp4H4LOW9Hjmy1Ev6lIJChy0AD4t
            Z6DEZwHdLZWIcyCRWmKfZyYPOYYB8g2em5VvV28CgYBbO9svw9OgG8E7qd3XEnBf
            ZM6IvkNRHJNx/OGw+vVOAVYL4QjAAOOL7Ne3teTSGXtOzt6AxbKt611HnJI9Fd2Q
            hS8QAbTWmetOB1zwTSRgAzESCgoUlQ3SC1K/dydX1k8lYxbpydjwOIT0OUrqNL2f
            ME6L4H3K6vhbR2ZilfbE8QKBgER6nsprsSYt0CCtVYFBgEr+PbvmopO3uduzpQNk
            LpRSndxcYruaNYxA9jfwcYLsAaIt/MV2l6BVF9pjTod6Qxk6Jj9+2NuI70G/yKmW
            1CId7qaP1u+UtdDwd7/IK6JbBAZazCXlne7Muqa08IRhZH7nAfgYpl00etxKUSwp
            9XWTAoGAFoJENS2q5k0b86blOYiBBTXQo2SreC8Uidr3PjRSR1koamhsnbNz9vZ+
            MhXeq4puvrUxw10zqmogho81HuYJrSsm3K8cIrRcFx7Tq+8G/Lnp0vNKya04GMDI
            NEqE55cyBebb+KpQILZU1ZZY32W7/5xys6sZcJVkiGhmCdLEMmY=
            -----END PRIVATE KEY-----
        google: |-
          {
          "type": "service_account",
          "project_id": "dummyproject",
          "private_key_id": "1111111111111111111111111111111111111111",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEogIBAAKCAQEA2ZUlwz6geaDZweWLH1yLjiRQ3l5oDl4gJBylCHE4XO3BTzVO\n3uvwduq9AvRVHBPhzWlBRzFMb9q8n6jlIdTkixdCE+LcJc2DYUfL58uiPtYP5fub\nbdkT8D9qtRkw/E8XL6zYltsLCajFMn96CgIywRMNb362ewpRrzz0jKpJjacPjgoV\nbH/68GImhRnD4gtdfzQ2J2gQ1rgnABHOZUgcw5aN1st71eqwEdJZqlbaJsaL64fG\nRv0SZFvXrbHPrWipSMv4nMlhCPD+OdvJwE0zQ3CVkORrm545E7GE+meEXEjFVzge\nfulrPWSnZgxFIwrNBNehk9+0MwTd9fbk8CpInwIDAQABAoIBACgBhmn5z+PNMXy3\nSfdAOuCtyLi6PwO1Rs+c/LMqriRYCt0XfiL62sHis1Ihvqxk83WjTr9aTyWZ4Giy\n0z5/OG5inmGtqrDAstFmNBWwmWpYTaAJvTBbY5Ee9+3IbftWR3samtBSAhuKjoeU\nbMn+UXqymBvR/pds9Ev2NzjN7qw+nn1gcupPNw0fpcEk7U4HT85oe2XmDOaCaoXB\n4ovLxzdRVnkHdNfp3tDMqVHLZrPP4bXbLi1+Tt4yF/JbDDXbY1pu+tebLW+xL5Zr\niLD5NZV2GH+EHj1oWB5utfVO2c+FDjJAvnceWnfEYuJ+p5g6nzV/C7o2lw7qnmpd\nHT0v5MECgYEA9jq/FjPMd+GRXMYV6rp9B9MGisRSA08lt0hDs5iKU2r5TB3c0hAq\nz3+suKJ7/8VxBxNmtduUt4r4rvAyB8gG5hWQtNSgis8COVC2QLBRRcvecjTcUhhA\nbOS8O0Sg8zVdfzeSaTMbQLFVtOYcBCvP7RYVXFn3CGOjgQZ64axfCdECgYEA4jdm\nWqSfQgqjAhIRWbU0DDbF/7iLZGiyUv3G4AA7XUWRMbItjO91jCE4feywT3SyaVEJ\nJEpXI4849sNMkZ4XwylTCCgO5WBqQmQWeHAuxp4H4LOW9Hjmy1Ev6lIJChy0AD4t\nZ6DEZwHdLZWIcyCRWmKfZyYPOYYB8g2em5VvV28CgYBbO9svw9OgG8E7qd3XEnBf\nZM6IvkNRHJNx/OGw+vVOAVYL4QjAAOOL7Ne3teTSGXtOzt6AxbKt611HnJI9Fd2Q\nhS8QAbTWmetOB1zwTSRgAzESCgoUlQ3SC1K/dydX1k8lYxbpydjwOIT0OUrqNL2f\nME6L4H3K6vhbR2ZilfbE8QKBgER6nsprsSYt0CCtVYFBgEr+PbvmopO3uduzpQNk\nLpRSndxcYruaNYxA9jfwcYLsAaIt/MV2l6BVF9pjTod6Qxk6Jj9+2NuI70G/yKmW\n1CId7qaP1u+UtdDwd7/IK6JbBAZazCXlne7Muqa08IRhZH7nAfgYpl00etxKUSwp\n9XWTAoGAFoJENS2q5k0b86blOYiBBTXQo2SreC8Uidr3PjRSR1koamhsnbNz9vZ+\nMhXeq4puvrUxw10zqmogho81HuYJrSsm3K8cIrRcFx7Tq+8G/Lnp0vNKya04GMDI\nNEqE55cyBebb+KpQILZU1ZZY32W7/5xys6sZcJVkiGhmCdLEMmY=\n-----END PRIVATE KEY-----\n",
          "client_email": "fffffffffffffffffffffff@g111111111111111111111111.com",
          "client_id": "111111111111111111111",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/1111111111111111111111111111111111111111111111111111111111111111111111111"
          }
    staging:
      main_app:
        apns:
          keyId: 'KEY_ID'
          teamId: 'TEAM_ID'
          data: |-
            -----BEGIN PRIVATE KEY-----
            MIIEogIBAAKCAQEA2ZUlwz6geaDZweWLH1yLjiRQ3l5oDl4gJBylCHE4XO3BTzVO
            3uvwduq9AvRVHBPhzWlBRzFMb9q8n6jlIdTkixdCE+LcJc2DYUfL58uiPtYP5fub
            bdkT8D9qtRkw/E8XL6zYltsLCajFMn96CgIywRMNb362ewpRrzz0jKpJjacPjgoV
            bH/68GImhRnD4gtdfzQ2J2gQ1rgnABHOZUgcw5aN1st71eqwEdJZqlbaJsaL64fG
            Rv0SZFvXrbHPrWipSMv4nMlhCPD+OdvJwE0zQ3CVkORrm545E7GE+meEXEjFVzge
            fulrPWSnZgxFIwrNBNehk9+0MwTd9fbk8CpInwIDAQABAoIBACgBhmn5z+PNMXy3
            SfdAOuCtyLi6PwO1Rs+c/LMqriRYCt0XfiL62sHis1Ihvqxk83WjTr9aTyWZ4Giy
            0z5/OG5inmGtqrDAstFmNBWwmWpYTaAJvTBbY5Ee9+3IbftWR3samtBSAhuKjoeU
            bMn+UXqymBvR/pds9Ev2NzjN7qw+nn1gcupPNw0fpcEk7U4HT85oe2XmDOaCaoXB
            4ovLxzdRVnkHdNfp3tDMqVHLZrPP4bXbLi1+Tt4yF/JbDDXbY1pu+tebLW+xL5Zr
            iLD5NZV2GH+EHj1oWB5utfVO2c+FDjJAvnceWnfEYuJ+p5g6nzV/C7o2lw7qnmpd
            HT0v5MECgYEA9jq/FjPMd+GRXMYV6rp9B9MGisRSA08lt0hDs5iKU2r5TB3c0hAq
            z3+suKJ7/8VxBxNmtduUt4r4rvAyB8gG5hWQtNSgis8COVC2QLBRRcvecjTcUhhA
            bOS8O0Sg8zVdfzeSaTMbQLFVtOYcBCvP7RYVXFn3CGOjgQZ64axfCdECgYEA4jdm
            WqSfQgqjAhIRWbU0DDbF/7iLZGiyUv3G4AA7XUWRMbItjO91jCE4feywT3SyaVEJ
            JEpXI4849sNMkZ4XwylTCCgO5WBqQmQWeHAuxp4H4LOW9Hjmy1Ev6lIJChy0AD4t
            Z6DEZwHdLZWIcyCRWmKfZyYPOYYB8g2em5VvV28CgYBbO9svw9OgG8E7qd3XEnBf
            ZM6IvkNRHJNx/OGw+vVOAVYL4QjAAOOL7Ne3teTSGXtOzt6AxbKt611HnJI9Fd2Q
            hS8QAbTWmetOB1zwTSRgAzESCgoUlQ3SC1K/dydX1k8lYxbpydjwOIT0OUrqNL2f
            ME6L4H3K6vhbR2ZilfbE8QKBgER6nsprsSYt0CCtVYFBgEr+PbvmopO3uduzpQNk
            LpRSndxcYruaNYxA9jfwcYLsAaIt/MV2l6BVF9pjTod6Qxk6Jj9+2NuI70G/yKmW
            1CId7qaP1u+UtdDwd7/IK6JbBAZazCXlne7Muqa08IRhZH7nAfgYpl00etxKUSwp
            9XWTAoGAFoJENS2q5k0b86blOYiBBTXQo2SreC8Uidr3PjRSR1koamhsnbNz9vZ+
            MhXeq4puvrUxw10zqmogho81HuYJrSsm3K8cIrRcFx7Tq+8G/Lnp0vNKya04GMDI
            NEqE55cyBebb+KpQILZU1ZZY32W7/5xys6sZcJVkiGhmCdLEMmY=
            -----END PRIVATE KEY-----
        google: |-
          {
          "type": "service_account",
          "project_id": "dummyproject",
          "private_key_id": "1111111111111111111111111111111111111111",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEogIBAAKCAQEA2ZUlwz6geaDZweWLH1yLjiRQ3l5oDl4gJBylCHE4XO3BTzVO\n3uvwduq9AvRVHBPhzWlBRzFMb9q8n6jlIdTkixdCE+LcJc2DYUfL58uiPtYP5fub\nbdkT8D9qtRkw/E8XL6zYltsLCajFMn96CgIywRMNb362ewpRrzz0jKpJjacPjgoV\nbH/68GImhRnD4gtdfzQ2J2gQ1rgnABHOZUgcw5aN1st71eqwEdJZqlbaJsaL64fG\nRv0SZFvXrbHPrWipSMv4nMlhCPD+OdvJwE0zQ3CVkORrm545E7GE+meEXEjFVzge\nfulrPWSnZgxFIwrNBNehk9+0MwTd9fbk8CpInwIDAQABAoIBACgBhmn5z+PNMXy3\nSfdAOuCtyLi6PwO1Rs+c/LMqriRYCt0XfiL62sHis1Ihvqxk83WjTr9aTyWZ4Giy\n0z5/OG5inmGtqrDAstFmNBWwmWpYTaAJvTBbY5Ee9+3IbftWR3samtBSAhuKjoeU\nbMn+UXqymBvR/pds9Ev2NzjN7qw+nn1gcupPNw0fpcEk7U4HT85oe2XmDOaCaoXB\n4ovLxzdRVnkHdNfp3tDMqVHLZrPP4bXbLi1+Tt4yF/JbDDXbY1pu+tebLW+xL5Zr\niLD5NZV2GH+EHj1oWB5utfVO2c+FDjJAvnceWnfEYuJ+p5g6nzV/C7o2lw7qnmpd\nHT0v5MECgYEA9jq/FjPMd+GRXMYV6rp9B9MGisRSA08lt0hDs5iKU2r5TB3c0hAq\nz3+suKJ7/8VxBxNmtduUt4r4rvAyB8gG5hWQtNSgis8COVC2QLBRRcvecjTcUhhA\nbOS8O0Sg8zVdfzeSaTMbQLFVtOYcBCvP7RYVXFn3CGOjgQZ64axfCdECgYEA4jdm\nWqSfQgqjAhIRWbU0DDbF/7iLZGiyUv3G4AA7XUWRMbItjO91jCE4feywT3SyaVEJ\nJEpXI4849sNMkZ4XwylTCCgO5WBqQmQWeHAuxp4H4LOW9Hjmy1Ev6lIJChy0AD4t\nZ6DEZwHdLZWIcyCRWmKfZyYPOYYB8g2em5VvV28CgYBbO9svw9OgG8E7qd3XEnBf\nZM6IvkNRHJNx/OGw+vVOAVYL4QjAAOOL7Ne3teTSGXtOzt6AxbKt611HnJI9Fd2Q\nhS8QAbTWmetOB1zwTSRgAzESCgoUlQ3SC1K/dydX1k8lYxbpydjwOIT0OUrqNL2f\nME6L4H3K6vhbR2ZilfbE8QKBgER6nsprsSYt0CCtVYFBgEr+PbvmopO3uduzpQNk\nLpRSndxcYruaNYxA9jfwcYLsAaIt/MV2l6BVF9pjTod6Qxk6Jj9+2NuI70G/yKmW\n1CId7qaP1u+UtdDwd7/IK6JbBAZazCXlne7Muqa08IRhZH7nAfgYpl00etxKUSwp\n9XWTAoGAFoJENS2q5k0b86blOYiBBTXQo2SreC8Uidr3PjRSR1koamhsnbNz9vZ+\nMhXeq4puvrUxw10zqmogho81HuYJrSsm3K8cIrRcFx7Tq+8G/Lnp0vNKya04GMDI\nNEqE55cyBebb+KpQILZU1ZZY32W7/5xys6sZcJVkiGhmCdLEMmY=\n-----END PRIVATE KEY-----\n",
          "client_email": "fffffffffffffffffffffff@g111111111111111111111111.com",
          "client_id": "111111111111111111111",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/1111111111111111111111111111111111111111111111111111111111111111111111111"
          }
  api-gateway:
    eqiad:
      main_app:
        jwks:
          kid: dummy
          key: dummy
    codfw:
      main_app:
        jwks:
          kid: dummy
          key: dummy
    staging:
      main_app:
        jwks:
          kid: dummy
          key: dummy
