profile::kubernetes::deployment_server::tokens:
  admin:
    token: dummy
  mathoid:
    token: dummy
  zotero:
    token: dummy
  graphoid:
    token: dummy
  blubberoid:
    token: dummy
  eventgate-analytics:
    token: dummytoken
  eventgate-main:
    token: dummytoken
  citoid:
    token: dummytoken
  cxserver:
    token: dummytoken
  sessionstore:
    token: dummytoken
  termbox:
    token: dummytoken

profile::kubernetes::deployment_server_secrets::services:
  zotero:
    staging:
      loooldata: a
