base_directory: /srv/private/modules/secret/secrets/cassandra/services/
authority:
  cert: &ca_cert
    subject:
      organization: WMF
      country: US
      unit: services
  password: placeholder

keystores:
  - name: restbase1001
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1001-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1001-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1001-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1002
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1002-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1002-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1002-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1003
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1003-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1003-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1003-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1004
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1004-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1004-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1004-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1005
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1005-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1005-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1005-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1006
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1006-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1006-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1006-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1007
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1007-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1007-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1007-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1008
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1008-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1008-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1008-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1009
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1009-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1009-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1009-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1010-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1010-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1010-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1011-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1011-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1011-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1012-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1012-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1012-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1013-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1013-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1013-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1014-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1014-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1014-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1015-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1015-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1015-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2001
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2001-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2001-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2001-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2002
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2002-a
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2002-b
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2002-c
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2003
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2004
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2005
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2006
    cert: 
      <<: *ca_cert
    password: placeholder
