authority:
  cert: &ca_cert
    subject:
      organization: WMF
      country: US
      unit: services
  password: placeholder

keystores:
  - name: restbase1001
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1002
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1003
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1004
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1005
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1006
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1007
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1008
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase1009
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2001
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2002
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2003
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2004
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2005
    cert: 
      <<: *ca_cert
    password: placeholder

  - name: restbase2006
    cert: 
      <<: *ca_cert
    password: placeholder
