# This CA can be used in the deployment-prep Cloud VPS project
# by the deployment-prep puppetmaster to sign certiifcates.
deployment_prep_puppet_ca:
  class_name: puppet
  # If the deployment-prep puppetmaster changes,
  # this will need to be changed too.
  hostname: deployment-puppetmaster02.deployment-prep.eqiad.wmflabs

kafka_jumbo-deployment-prep_broker:
  authority: deployment_prep_puppet_ca
  expiry: null
  key:
    password: qwerty
    algorithm: ec

kafka_main-deployment-prep_broker:
  authority: deployment_prep_puppet_ca
  expiry: null
  key:
    password: qwerty
    algorithm: ec

varnishkafka-deployment-prep:
  authority: deployment_prep_puppet_ca
  expiry: null
  key:
    password: qwerty
    algorithm: ec

# Certificate to test Kafka clients and ACLs.
kafka_test:
  authority: deployment_prep_puppet_ca
  expiry: null
  key:
    password: qwerty
    algorithm: ec
