swift::params::replication_keys:
    mw_media:
        key:  'key1'
        key2: 'key2'
    docker_registry:
        key:  'key1'
        key2: 'key2'


swift::params::account_keys:
    super_admin: dummy
    mw_media: dummy
    mw_thumbor: dummy
    mw_thumbor-private: dummy
    dispersion: dummy
    search_backup: dummy
    docker_registry: dummy
    pagecompilation_zim: dummy
    phabricator_files: dummy
    analytics_admin: dummy
    netbox_attachments: dummy

swift::params::account_temp_url_keys:
    mw_media: dummy

swift::params::replication_accounts:
    docker_registry:
        cluster_codfw: 'https://swift.svc.codfw.wmnet/v1'
        cluster_eqiad: 'https://swift.svc.eqiad.wmnet/v1'
    mw_media:
        cluster_codfw: 'https://ms-fe.svc.codfw.wmnet/v1/'
